server:
  port: 8888

spring:
  application:
    name: api-gateway
  main:
    web-application-type: REACTIVE
  datasource:
    url: none
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**,/api/v1/history/**,/api/v1/shipping-address/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/payment/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/order/**

logging:
  level:
    org.springframework.web: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG
    io.netty.handler.ssl: DEBUG